### ISSUE TITLE
Split package so library-only code doesn't pull in Scribble

### ISSUE THREAD

**Issue by wilbowma** [jbclements/memoize#6]
It would be helpful to users to have `-lib`, `-doc` packages separated out. I'm willing to do the work if you're willing to merge it.

**Comment by wilbowma** [comment]
Ping; any interest in this?

**Comment by jbclements** [comment]
Yep, sounds great! I accept your pull request before it even exists!

John

**Comment by wilbowma** [comment]
Oh i put the comment in the wrong place, because the pull request already exists: #7
