### ISSUE TITLE
#7 breaks installation

### ISSUE THREAD

**Issue by mathsaey** [jbclements/memoize#8]
It is currently not possible to install packages that (indirectly) depend on memoize due to the changes made in #7.

At the very least, this breaks http-easy and other packages depending on it.

I am not that familiar with racket packaging, but perhaps the changes suggested by @sorawee [here](https://github.com/jbclements/memoize/pull/7#issuecomment-1006452945) might be a good starting point to fix this?

**Comment by jbclements** [comment]
Yes, my sincere apologies. In principle, the situation now should be better than it was before, because it should now be possible for packages to depend only on memoize-lib, thus eliminating the scribble dependencies. At this point, existing packages should now also continue to work.

**Comment by jbclements** [comment]
Closing this, let me know if I should re-open.

**Comment by mathsaey** [comment]
Can confirm things seem to be working again on my end. Thanks for the quick fix!
